# Generated by Django 4.1.5 on 2023-02-13 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('size', models.CharField(choices=[('Large', 'Large'), ('Medium', 'Medium'), ('Small', 'Small')], default='Small', max_length=6)),
                ('crust', models.CharField(choices=[('Normal', 'Normal'), ('Thin', 'Thin'), ('Thick', 'Thick')], default='Normal', max_length=6)),
                ('sauce', models.CharField(choices=[('Tomato', 'Tomato'), ('BBQ', 'BBQ')], default='Tomato', max_length=6)),
                ('Pepperoni', models.BooleanField(default=False)),
                ('Chicken', models.BooleanField(default=False)),
                ('Ham', models.BooleanField(default=False)),
                ('Pineapple', models.BooleanField(default=False)),
                ('Peppers', models.BooleanField(default=False)),
                ('Mushrooms', models.BooleanField(default=False)),
                ('Onions', models.BooleanField(default=False)),
            ],
        ),
    ]
