# Generated by Django 4.1.5 on 2023-02-14 14:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PizzaOrder', '0002_pizzaorder_cheese'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('address', models.TextField()),
                ('card', models.BigIntegerField()),
                ('expiry', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
