# Generated by Django 4.1.5 on 2023-02-14 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PizzaOrder', '0003_deliverydetails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeliveryDetails',
            new_name='DeliveryDetail',
        ),
    ]
