# Generated by Django 4.1.6 on 2023-02-15 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PizzaOrder', '0005_deliverydetail_pizza_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverydetail',
            name='address',
        ),
        migrations.AddField(
            model_name='deliverydetail',
            name='address1',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='deliverydetail',
            name='address2',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='deliverydetail',
            name='address3',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='deliverydetail',
            name='county',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='deliverydetail',
            name='eircode',
            field=models.CharField(default='', max_length=7),
        ),
    ]
