# Generated by Django 4.1.6 on 2023-02-15 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PizzaOrder', '0006_remove_deliverydetail_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverydetail',
            name='address1',
        ),
        migrations.RemoveField(
            model_name='deliverydetail',
            name='address2',
        ),
        migrations.RemoveField(
            model_name='deliverydetail',
            name='address3',
        ),
        migrations.AddField(
            model_name='deliverydetail',
            name='address',
            field=models.TextField(default=''),
        ),
    ]
