# Generated by Django 4.1.6 on 2023-02-15 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PizzaOrder', '0008_remove_deliverydetail_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverydetail',
            name='first_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='deliverydetail',
            name='last_name',
            field=models.CharField(max_length=20),
        ),
    ]
