# Generated by Django 4.1.6 on 2023-02-15 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PizzaOrder', '0009_alter_deliverydetail_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverydetail',
            name='address3',
        ),
    ]
