# Generated by Django 4.1.5 on 2023-02-20 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PizzaOrder', '0010_remove_deliverydetail_address3'),
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaCheese',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cheese', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PizzaCrust',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('crust', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PizzaSauce',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sauce', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PizzaSize',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='pizzaorder',
            name='cheese',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PizzaOrder.pizzacheese'),
        ),
        migrations.AlterField(
            model_name='pizzaorder',
            name='crust',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PizzaOrder.pizzacrust'),
        ),
        migrations.AlterField(
            model_name='pizzaorder',
            name='sauce',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PizzaOrder.pizzasauce'),
        ),
        migrations.AlterField(
            model_name='pizzaorder',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PizzaOrder.pizzasize'),
        ),
    ]
