# Generated by Django 4.1.5 on 2023-02-20 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PizzaOrder', '0011_pizzacheese_pizzacrust_pizzasauce_pizzasize_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizzasize',
            name='size',
            field=models.TextField(default=''),
        ),
    ]
