# Generated by Django 4.1.5 on 2023-02-20 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PizzaOrder', '0015_alter_pizzaorder_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzaorder',
            name='cheese',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PizzaOrder.pizzacheese'),
        ),
        migrations.AlterField(
            model_name='pizzaorder',
            name='crust',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PizzaOrder.pizzacrust'),
        ),
        migrations.AlterField(
            model_name='pizzaorder',
            name='sauce',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PizzaOrder.pizzasauce'),
        ),
    ]
