# Generated by Django 4.1.6 on 2023-02-20 20:40

import PizzaOrder.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PizzaOrder', '0016_alter_pizzaorder_cheese_alter_pizzaorder_crust_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverydetail',
            name='card',
            field=models.BigIntegerField(validators=[PizzaOrder.models.validate_card]),
        ),
    ]
