# Generated by Django 4.1.6 on 2023-02-20 20:56

import PizzaOrder.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PizzaOrder', '0017_alter_deliverydetail_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverydetail',
            name='address2',
        ),
        migrations.AlterField(
            model_name='deliverydetail',
            name='expiry',
            field=models.TextField(max_length=5),
        ),
    ]
