# Generated by Django 4.1.6 on 2023-02-20 21:13

import PizzaOrder.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PizzaOrder', '0019_alter_deliverydetail_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverydetail',
            name='card',
            field=models.IntegerField(validators=[PizzaOrder.models.validate_card]),
        ),
    ]
