# Generated by Django 4.1.6 on 2023-02-20 21:13

import PizzaOrder.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PizzaOrder', '0019_alter_deliverydetail_expiry'),
    ]

    operations = [
    ]