# Generated by Django 4.1.6 on 2023-02-21 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PizzaOrder', '0021_alter_deliverydetail_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverydetail',
            name='cvv',
            field=models.IntegerField(default=0),
        ),
    ]
