# Generated by Django 4.1.6 on 2023-02-21 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PizzaOrder', '0022_deliverydetail_cvv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverydetail',
            name='pizza_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PizzaOrder.pizzaorder'),
        ),
    ]
