# Generated by Django 4.1.6 on 2023-02-21 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PizzaOrder', '0023_alter_deliverydetail_pizza_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverydetail',
            name='address2',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='deliverydetail',
            name='pizza_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PizzaOrder.pizzaorder'),
        ),
    ]
