# Generated by Django 4.1.6 on 2023-02-21 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PizzaOrder', '0024_deliverydetail_address2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliverydetail',
            old_name='county',
            new_name='city',
        ),
    ]
