# Generated by Django 4.1.6 on 2023-02-21 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PizzaOrder', '0026_deliverydetail_county'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverydetail',
            name='cvv',
            field=models.CharField(max_length=3),
        ),
    ]
