# Generated by Django 4.1.6 on 2023-02-22 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PizzaOrder', '0029_alter_deliverydetail_eircode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverydetail',
            name='cvv',
            field=models.CharField(max_length=3),
        ),
    ]
