# Generated by Django 4.1.5 on 2023-02-23 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PizzaOrder', '0030_alter_deliverydetail_cvv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverydetail',
            name='pizza_order',
        ),
    ]
