# Generated by Django 4.1.5 on 2023-02-23 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PizzaOrder', '0031_remove_deliverydetail_pizza_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverydetail',
            name='pizza_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PizzaOrder.pizzaorder'),
        ),
    ]
