# Generated by Django 4.1.5 on 2023-03-01 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PizzaOrder', '0034_deliverydetail_pizza_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverydetail',
            name='pizza_order',
        ),
    ]
