# Generated by Django 4.1.5 on 2023-02-01 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_borrowing_book_borrowing_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='name',
            field=models.TextField(),
        ),
    ]
