# Generated by Django 4.1.5 on 2023-02-02 21:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_borrowing_borrowed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowing',
            name='due_date',
            field=models.DateField(default=datetime.date(2023, 2, 9)),
        ),
    ]
