# Generated by Django 3.2.15 on 2023-03-06 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ca298shop', '0002_auto_20230306_1116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='sizes',
            new_name='size',
        ),
    ]
